weird error about floating point
RuntimeError: Input type (c10::Half) and bias type (float) should be the same

this appeared out of nowhere, i'm not sure what it means, but i'm
going to remove any reference to fp16 since i don't think i need it
anyway